package bcit.ca.infosys.KeyboardCowboys.util;


import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.List;

import bcit.ca.infosys.KeyboardCowboys.model.TimeRow;
import bcit.ca.infosys.KeyboardCowboys.model.TimeSheet;

/**
 * Class that will serialize a timesheet into a byte array. The 
 * generated byte array will be used when creating digital sigs.
 * @author Jitin Dhillon
 *
 */
public class TimeSerializer {

	/**
	 * Takes a timesheet object and serializes it into a byte array for signature generation.
	 * @param Time Timesheet to be serialized.
	 * @return Byte array of serialized timesheet.
	 * @throws IOException
	 */
	public static byte[] SerializeTimeSheet(TimeSheet time) throws IOException {
		String data = null;
		
		List<TimeRow> rows = time.getTsTimeRows();
		
		data += time.getTsID().toString();
		
		for(TimeRow t: rows){
		}
		
		ByteArrayOutputStream b = new ByteArrayOutputStream();
		ObjectOutputStream o = new ObjectOutputStream(b);
		o.writeObject(time);
		return b.toByteArray();
	}
}
